# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: add gradlew permissions
      run: chmod +x ./gradlew
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    # Configure Gradle for optimal use in GiHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Build with Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
      with:
         arguments: build jacocoTestReport
         
    - name: Upload JaCoCo coverage report as a workflow artifact
      uses: actions/upload-artifact@v3.1.1
      with:
       name: jacoco-report
       path: tests/build/reports/jacoco/test/html  

    - name: Upload library JAR
      uses: actions/upload-artifact@v3.1.1
      with:
       name: lib.jar
       path: tests/build/libs/lib.jar
    - name: Build with Gradle Wrapper
      run: ./gradlew build

   
